[build]
  publish   = "."
  functions = "netlify/functions"

# Security headers & CSP
[[headers]]
  for = "/*"
  X-Frame-Options            = "DENY"
  X-XSS-Protection           = "1; mode=block"
  X-Content-Type-Options     = "nosniff"
  Referrer-Policy            = "strict-origin-when-cross-origin"
  Content-Security-Policy    = """
    default-src 'self';
    script-src 'self' https://cdn.jsdelivr.net;
    style-src 'self' 'unsafe-inline';
    img-src 'self' https://i.postimg.cc data:;
    connect-src 'self' https://truyenhdt.com/;
  """


